app:
  build: .
  volumes:
    - /Users/guilhermes/projects/docker-images/railsApp/:/myapp
  ports:
    - "3000:3000"
  links:
    - mysql
  command: 
    - "./start-docker.sh"

mysql:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "root"  